language: php

php:
  - '5.5'

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e 'CREATE DATABASE esnp;'
  - composer install --dev --no-interaction --prefer-source
  - app/console doctrine:fixtures:load

script:
  - phpunit --coverage-text

notifications:
  email:

notifications:
  email:
    recipients:
      - jeremie.samson@ix.esnlille.fr
    on_success: [never]
    on_failure: [always]