language: php

php:
  - '5.5'

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --dev --no-interaction --prefer-source
  - app/console doctrine:database:create --env=test --no-interaction --quiet
  - app/console cache:warmup --env=test --quiet

script:
  - phpunit

notifications:
  email:

notifications:
  email:
    recipients:
      - webmaster@esnlille.fr
    on_success: [never]
    on_failure: [always]