<?php

namespace AppBundle\Repository;

/**
 * OCMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OCMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
