imports:
    - { resource: config.yml }
    - { resource: security_api.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_api.yml"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: streamed
        streamed:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        login:
            type: stream
            path: "%kernel.logs_dir%/auth.log"
            level: error
            channels: security
        firephp:
            type:  firephp
            level: error
        chromephp:
            type:  chromephp
            level: error

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: ['*']
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            expose_headers: ['*']
            max_age: 3600